DROP TABLE MEMBER;
CREATE TABLE MEMBER(
MEMBER_NO NUMBER PRIMARY KEY,
MEMBER_ID VARCHAR2(15) NOT NULL UNIQUE,
MEMBER_PWD VARCHAR2(30) NOT NULL,
MEMBER_NAME VARCHAR2(20) NOT NULL,
MEMBER_EMAIL VARCHAR2(30) NOT NULL UNIQUE,
MEMBER_BIRTH  VARCHAR2(20),
MEMBER_JOIN_DATE TIMESTAMP,
MEMBER_ROLE CHAR(1) DEFAULT 'C' CHECK(MEMBER_ROLE IN ('C','A')),
MEMBER_QUIT_YN CHAR(1) DEFAULT 'N' CHECK(MEMBER_QUIT_YN IN ('Y','N'))
);

DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER NOCYCLE NOCACHE;

INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_EMAIL, MEMBER_ROLE)
VALUES (SEQ_MEMBER.NEXTVAL, 'admin1', 'rhksflwk1#', '주관리자', 'admin1@naver.com','A');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_EMAIL, MEMBER_ROLE)
VALUES (SEQ_MEMBER.NEXTVAL, 'admin2', 'rhksflwk2$', '상품관리자', 'admin2@naver.com','A');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_EMAIL, MEMBER_ROLE)
VALUES (SEQ_MEMBER.NEXTVAL, 'admin3', 'rhksflwk3%', '게시글관리자', 'admin3@naver.com','A');

commit;
SELECT * FROM MEMBER;

DELETE FROM MEMBER WHERE MEMBER_ID = 'skekkjim13';






