-------------------------------생성부
CREATE TABLE PRODUCT (
    PRODUCT_NO     NUMBER PRIMARY KEY,
    PRODUCT_NAME   VARCHAR2(50) NOT NULL UNIQUE,
    PRODUCT_PRICE  NUMBER NOT NULL,
    PRODUCT_STOCK  NUMBER NOT NULL,
    PRODUCT_IMAGE  VARCHAR2(200) NOT NULL,
    PRODUCT_COLOR  VARCHAR2(50),
    FLOWER_LANG    VARCHAR2(50),
    PRODUCT_SIMPLE VARCHAR2(50),
    PRODUCT_DETAIL VARCHAR2(200),
    PRODUCT_SIZE   CHAR(1) DEFAULT 'M' CHECK ( PRODUCT_SIZE IN ( 'S', 'M', 'L' ) ),
    DISCOUNT_RATE  NUMBER,
    SALE_STATUS    CHAR(1) DEFAULT 'Y' CHECK ( SALE_STATUS IN ( 'Y', 'N' ) ),
		REGISTER_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE SEQ_PRODUCT NOCYCLE NOCACHE;

CREATE TABLE QUESTION (
Q_NO    NUMBER PRIMARY KEY,
M_NO    NUMBER NOT NULL,
Q_TITLE  VARCHAR2(200) NOT NULL,
Q_CONTENT   VARCHAR2(3000) NOT NULL,
Q_CREATE  TIMESTAMP,
Q_RESPONSE CHAR(1) DEFAULT 'N' CHECK(Q_RESPONSE IN ('Y','N')),
Q_DELETED  CHAR(1) DEFAULT 'N' CHECK(Q_DELETED IN ('Y','N'))
);

CREATE SEQUENCE SEQ_QUESTION NOCYCLE NOCACHE;

CREATE TABLE QUESTION_RESPONSE(
    R_NO    NUMBER PRIMARY KEY,
    Q_NO    NUMBER UNIQUE,
    M_NO    NUMBER NOT NULL,
    ADMIN_ID VARCHAR2(15) NOT NULL,
    R_CONTENT   VARCHAR2(3000) NOT NULL,
    R_CREATE    TIMESTAMP,
    R_DELETED CHAR(1) DEFAULT 'N' CHECK(R_DELETED IN ('Y','N')),
    
    CONSTRAINT Q_NO_FK FOREIGN KEY(Q_NO)REFERENCES QUESTION(Q_NO)
);

CREATE SEQUENCE SEQ_QUESTION_RESPONSE NOCYCLE NOCACHE;

CREATE TABLE BOUQUET (
    BOUQUET_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    BOUQUET_NAME VARCHAR2(30) NOT NULL,
    WRAP_COLOR VARCHAR2(10) NOT NULL,
    BOUQUET_PRICE NUMBER
);

CREATE SEQUENCE SEQ_BOUQUET NOCYCLE NOCACHE;

CREATE TABLE CURRENT_FLOWER (
    CF_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    PRODUCT_NO NUMBER NOT NULL,
    PRODUCT_NAME VARCHAR2(50) NOT NULL,
    ORDER_NUM NUMBER,
    PRODUCT_PRICE NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_CF NOCYCLE NOCACHE;

CREATE TABLE MEMBER_GRADE(
GRADE_NO NUMBER PRIMARY KEY CHECK(GRADE_NO IN (100,200,999)),
GRADE_NAME VARCHAR2(15) DEFAULT '일반회원' CHECK(GRADE_NAME IN ('일반회원','VIP','관리자')) ,
POINT_RATE NUMBER DEFAULT 0.01 CHECK(POINT_RATE IN (0.01,0.05,0.1))
);

CREATE TABLE MEMBER(
MEMBER_NO NUMBER PRIMARY KEY,
GRADE_NO NUMBER DEFAULT 100,
MEMBER_ID VARCHAR2(20) NOT NULL UNIQUE,
MEMBER_PWD VARCHAR2(500) NOT NULL,
MEMBER_NAME VARCHAR2(20) NOT NULL,
MEMBER_EMAIL VARCHAR2(40) NOT NULL UNIQUE,
MEMBER_BIRTH  VARCHAR2(20),
MEMBER_JOIN_DATE TIMESTAMP,
MEMBER_ROLE CHAR(1) DEFAULT 'C' CHECK(MEMBER_ROLE IN ('C','A')),
MEMBER_QUIT_YN CHAR(1) DEFAULT 'N' CHECK(MEMBER_QUIT_YN IN ('Y','N')),
MEMBER_POINT NUMBER DEFAULT 0,
MEMBER_ORDER_SUM NUMBER DEFAULT 0,
CONSTRAINT GRADE_NO_FK FOREIGN KEY(GRADE_NO)REFERENCES MEMBER_GRADE(GRADE_NO)
);

CREATE SEQUENCE SEQ_MEMBER NOCYCLE NOCACHE 
START WITH 13985 INCREMENT BY 1;

CREATE TABLE CART(
		CART_NO NUMBER PRIMARY KEY,
		MEMBER_NO NUMBER NOT NULL,
		BOUQUET_NO NUMBER NOT NULL,
		BOUQUET_NAME VARCHAR2(100) NOT NULL,
		BOUQUET_DETAIL VARCHAR2(900) NOT NULL,
		BUY_NUM_BQ NUMBER DEFAULT 1 NOT NULL,
	CONSTRAINT MEMBER_NO_PFK FOREIGN KEY(MEMBER_NO)REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT BOUQUET_NO_FK FOREIGN KEY(BOUQUET_NO)REFERENCES BOUQUET(BOUQUET_NO)
);

CREATE SEQUENCE SEQ_CART NOCYCLE NOCACHE
START WITH 35247 INCREMENT BY 1;

DROP TABLE ORDERLIST;
CREATE TABLE ORDERLIST(
ORDER_NO NUMBER PRIMARY KEY,
BOUQUET_NO NUMBER NOT NULL,
MEMBER_NO NUMBER NOT NULL,
ORDER_NUM NUMBER NOT NULL,
DELIVERY_STATE VARCHAR2(20) DEFAULT '결제완료' CHECK ( DELIVERY_STATE IN ( '결제완료', '배송준비', '배송중' , '배송완료' )),
ORDER_PRICE NUMBER  NOT NULL,
POINT_NY CHAR(1) DEFAULT 'N' CHECK ( DELIVERY_STATE IN ('N', 'Y')),
PPOINT_USED NUMBER,
ORDER_DATE TIMESTAMP,

CONSTRAINT BOUQUET_NO_FK2 FOREIGN KEY(BOUQUET_NO)REFERENCES BOUQUET(BOUQUET_NO),
CONSTRAINT MEMBER_NO_FK2 FOREIGN KEY(MEMBER_NO)REFERENCES MEMBER(MEMBER_NO)
);

CREATE SEQUENCE SEQ_ORDERLIST NOCYCLE NOCACHE
START WITH 2201964 INCREMENT BY 1;

CREATE TABLE REVIEW (
    REVIEW_NO NUMBER PRIMARY KEY,
    BOUQUET_NO NUMBER,
    MEMBER_ID VARCHAR2(15),
		BOUQUET_NAME VARCHAR2(30),
    REVIEW_TITLE VARCHAR2(100),
    REVIEW_IMAGE  VARCHAR2(200),
    REVIEW_CONTENT VARCHAR2(500),
    REVIEW_DATE DATE DEFAULT SYSDATE,
    STARS NUMBER CHECK(STARS BETWEEN 1 AND 5),
    REVIEW_DELETED CHAR(1) DEFAULT 'N' CHECK ( REVIEW_DELETED IN ( 'Y', 'N' ) )
    
    ---FOREIGN KEY (ORDER_NO) REFERENCES ORDERLIST(ORDER_NO) 
);

CREATE SEQUENCE SEQ_REVIEW NOCYCLE NOCACHE;

-----------------------------------------------------------------------------
-------------------------------기본값 추가

INSERT INTO MEMBER(MEMBER_NO, GRADE_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_EMAIL, MEMBER_ROLE)
VALUES (1, 999, 'admin1', 'rhksflwk1#', '주관리자', 'admin1@naver.com','A');
INSERT INTO MEMBER(MEMBER_NO, GRADE_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_EMAIL, MEMBER_ROLE)
VALUES (2, 999, 'admin2', 'rhksflwk2$', '상품관리자', 'admin2@naver.com','A');
INSERT INTO MEMBER(MEMBER_NO, GRADE_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_EMAIL, MEMBER_ROLE)
VALUES (3, 999, 'admin3', 'rhksflwk3%', '게시글관리자', 'admin3@naver.com','A');

INSERT INTO MEMBER_GRADE
VALUES (100, '일반회원', 0.01);
INSERT INTO MEMBER_GRADE
VALUES (200, 'VIP', 0.05);
INSERT INTO MEMBER_GRADE
VALUES (999, '관리자', 0.1);

INSERT INTO CART VALUES (SEQ_CART.NEXTVAL, 4, 5, '장미', DEFAULT);
INSERT INTO CART VALUES (SEQ_CART.NEXTVAL, 4, 6, '장미', DEFAULT);
INSERT INTO CART VALUES (SEQ_CART.NEXTVAL, 4, 7, '장미', DEFAULT);
INSERT INTO CART VALUES (SEQ_CART.NEXTVAL, 4, 8, '해바라기', DEFAULT);

INSERT INTO ORDERLIST(ORDER_NO, BOUQUET_NO, MEMBER_NO, DELIVERY_STATE, ORDER_PRICE)
VALUES (SEQ_MEMBER.NEXTVAL, 5, 4, DEFAULT, 40000);
INSERT INTO ORDERLIST(ORDER_NO, BOUQUET_NO, MEMBER_NO, DELIVERY_STATE, ORDER_PRICE)
VALUES (SEQ_MEMBER.NEXTVAL, 2, 5, DEFAULT, 53000);
INSERT INTO ORDERLIST(ORDER_NO, BOUQUET_NO, MEMBER_NO, DELIVERY_STATE, ORDER_PRICE)
VALUES (SEQ_MEMBER.NEXTVAL, 4, 7, DEFAULT, 38000);
INSERT INTO ORDERLIST(ORDER_NO, BOUQUET_NO, MEMBER_NO, DELIVERY_STATE, ORDER_PRICE)
VALUES (SEQ_MEMBER.NEXTVAL, 3, 4, DEFAULT, 29000);
INSERT INTO ORDERLIST(ORDER_NO, BOUQUET_NO, MEMBER_NO, DELIVERY_STATE, ORDER_PRICE)
VALUES (SEQ_MEMBER.NEXTVAL, 1, 6, DEFAULT, 61000);

-----------------------------------------------------------------------------
-------------------------------검색

SELECT * FROM PRODUCT;

SELECT * FROM QUESTION;

SELECT * FROM QUESTION_RESPONSE;

SELECT * FROM MEMBER;

SELECT * FROM CART;

SELECT * FROM ORDERLIST;

SELECT * FROM CURRENT_FLOWER;

SELECT * FROM BOUQUET;

SELECT * FROM REVIEW;


-----------------------------------------------------------------------------
-------------------------------삭제


DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_PRODUCT;
DROP TABLE QUESTION CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_QUESTION;
DROP TABLE QUESTION_RESPONSE CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_QUESTION_RESPONSE;
DROP TABLE MEMBER_GRADE;
DROP TABLE BOUQUET;
DROP SEQUENCE SEQ_BOUQUET;
DROP TABLE CURRENT_FLOWER;
DROP SEQUENCE SEQ_CF;
DROP TABLE MEMBER;
DROP SEQUENCE SEQ_MEMBER;
DROP TABLE CART;
DROP SEQUENCE SEQ_CART;
DROP TABLE ORDERLIST;
DROP SEQUENCE SEQ_ORDERLIST;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_REVIEW;